name: webkit_inspection_protocol
version: 0.1.0
description: A client for the Webkit Inspection Protocol (WIP).

homepage: https://github.com/google/webkit_inspection_protocol.dart
author: Devon Carew <devoncarew@google.com>

environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  args: '^0.13.1'
  logging: '^0.11.0'
  shelf: '^0.6.1+2'
  shelf_web_socket: '^0.0.1+2'
dev_dependencies:
  shelf_static: '^0.2.2'
  test: '^0.12.0'
